### ISSUE TITLE
Problems with I > 0.01

### ISSUE THREAD

**Issue by jpuritz** [dereneaton/simrrls#2]
I get this error when I try to use an INDEL rate > 0.1:

```
simrrls -I 0.02
```

```
Traceback (most recent call last):
  File "/usr/bin/simrrls", line 9, in <module>
    load_entry_point('simrrls==0.0.9', 'console_scripts', 'simrrls')()
  File "/usr/lib/python2.7/site-packages/simrrls/__main__.py", line 17, in main
    run(params)
  File "/usr/lib/python2.7/site-packages/simrrls/simrrls.py", line 538, in run
    counter, stepsize)
  File "/usr/lib/python2.7/site-packages/simrrls/simrrls.py", line 358, in seq_copies
    if tempseq[iloc] != outseq[iloc]:
IndexError: string index out of range
```

**Comment by dereneaton** [comment]
This is now fixed.
