### ISSUE TITLE
Attribute error 'module' object has no attribute 'simul' 

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [dereneaton/simrrls#4]
Hi,
I have run into a similar problem as reported in issue #3.

When I call simrrls I get the following error message: 
$ simrrls
Traceback (most recent call last):
File "/Users/ClaudiaPaetzold/anaconda2/bin/simrrls", line 9, in 
load_entry_point('simrrls==0.0.10', 'console_scripts', 'simrrls')()
File "build/bdist.macosx-10.5-x86_64/egg/simrrls/main.py", line 17, in main
File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 464, in run
File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 29, in checkopts
File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 87, in defaulttree
AttributeError: 'module' object has no attribute 'simul'

However, following your advice from issue #3 I have installed eggless v2.1.11. 
Yet the error remains.
Any hints?

P.S. python v 2.7.11
numpy v1.11.0

Any help is appreciated. Thank You

**Comment by dereneaton** [comment]
Hi Claudia, 

Installing egglib can be pretty tricky. It's possible that you still have the wrong version installed. Try opening a Python session and typing the following: 

```
import egglib
print egglib.version
```

It should print something like the following, not v.3.0+:

```
2.1.10

```

**Comment by ClaudiaPaetzold** [comment]
Hex Deren,

thanks for the advice. You were right, egglib v 3 was not uninstalled completely. Now it's the right version. Thank You. I'm going to close the issue.

Cheers.
